options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Authenticate with Google Cloud (optional, but recommended)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/submit-jokes:$COMMIT_SHA', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/submit-jokes:$COMMIT_SHA']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'submit-jokes--staging'
      - '--image'
      - 'gcr.io/$PROJECT_ID/submit-jokes:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/submit-jokes:$COMMIT_SHA'

serviceAccount: '502810113594-compute@developer.gserviceaccount.com'
