options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Authenticate with Google Cloud (optional, but recommended)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/submit-jokes:$COMMIT_SHA', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/submit-jokes:$COMMIT_SHA']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'submit-jokes'
      - '--image'
      - 'gcr.io/$PROJECT_ID/submit-jokes:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
       - '--set-env-vars=MONGODB_URI=mongodb+srv://jokeUser:cc09UC26vEdEGU92@jokescluster.gqctc.mongodb.net/jokesDatabase?retryWrites=true&w=majority'
      - '--allow-unauthenticated'
substitutions:
  _SERVICE_NAME: submit-jokes
  _REGION: us-central1
images:
  - 'gcr.io/$PROJECT_ID/submit-jokes:$COMMIT_SHA'

serviceAccount: '502810113594-compute@developer.gserviceaccount.com'
